export default {
  // The explorable world is a set of zones. Pure data: each zone is a tile grid drawn
  // as strings + a legend (which characters are solid), plus an object layer for NPCs,
  // "portals" (open a math activity), and "warps" (travel to another zone).
  //   legend codes: '.' grass · '#' path · '~' pond(solid) · 'T' tree(solid)
  //                 'H' house(solid) · '*' flowers
  // `order` drives the fast-travel Map list.
  order: ['town', 'meadow', 'gardens', 'falls', 'docks', 'castle'],
  zones: {
    town: {
      name: 'Town Square', emoji: '🏙️', tile: 40, spawn: { col: 5, row: 10 },
      legend: { '.': {}, '#': {}, '~': { solid: true }, 'T': { solid: true }, 'H': { solid: true }, '*': {} },
      quest: {
        id: 'q-town-helper', name: 'Sunny', emoji: '🐥', goal: 2,
        reward: { coins: 25, decor: 'decor-painting' },
        lines: {
          intro: 'Will you help 2 friends with their math today? 🐥',
          active: 'You\'ve helped {n} of 2 friends — keep going!',
          done: 'You did it! Here\'s a painting for your home! 🎨🎉',
          thanks: 'Thanks again, friend! 💖',
        },
      },
      rows: [
        'TTTTTTTTTTTTTTTTTTTT',
        'T..................T',
        'T...*....##....*...T',
        'T........##........T',
        'T..~~....##.....HH.T',
        'T..~~....##.....HH.T',
        'T........##........T',
        'T##################T',
        'T........##........T',
        'T...*....##....*..#T',
        'T........##.......#T',
        'T........##........T',
        'T..................T',
        'TTTTTTTTTTTTTTTTTTTT',
      ],
      objects: [
        { type: 'encounter', col: 10, row: 6, emoji: '🦉', name: 'Professor Owl', strand: 'Multiplication',
          say: 'Ah, a visitor! Help me with a number puzzle? 🦉' },
        { type: 'encounter', col: 4,  row: 4, emoji: '🦫', name: 'Builder Beaver', strand: 'Addition & Subtraction',
          wordProblem: true, say: 'I\'m building a dam and I\'m all muddled up — can you help me work out a number? 🪵' },
        { type: 'boss', col: 7, row: 11, emoji: '🤖', name: 'Count Bot', strand: 'Addition & Subtraction',
          id: 'boss-town', questions: 2, sticker: { glyph: '⚙️', name: 'Robot Gear' }, reward: { coins: 35, decor: 'decor-bookshelf' },
          say: 'BEEP BOOP. SOLVE TWO TO PASS! 🤖', lines: { win: 'SYSTEMS IMPRESSED! 🤖🏆', done: 'YOU.WIN.ALREADY. 👍' } },
        { type: 'quest',     col: 4,  row: 2, emoji: '🐥', name: 'Sunny',          say: 'Got a minute, friend? 🐥' },
        { type: 'minigame',  col: 6,  row: 2, emoji: '🌟', name: 'Star Game' },
        { type: 'npc',       col: 13, row: 3, emoji: '🐻', name: 'Mayor Bramble', id: 'npc-mayor',
          lines: ['Welcome to MathQuest Island! 🐻', 'Each friend here loves a different kind of math.', 'Help them all, and our island will grow!'] },
        { type: 'portal',    col: 15, row: 6, emoji: '✨', name: 'Practice Portal', to: '#/play',
          say: 'Step into the sparkles to practice anything! ✨' },
        { type: 'warp',      col: 17, row: 9, emoji: '🌾', name: 'Path to the Meadow', to: 'meadow', toSpawn: { col: 3, row: 9 },
          say: 'Off to Multiplication Meadow! 🌾' },
        { type: 'warp',      col: 2,  row: 11, emoji: '🌳', name: 'Path to the Gardens', to: 'gardens', toSpawn: { col: 3, row: 10 },
          say: 'Off to Geometry Gardens! 🌳' },
        { type: 'warp',      col: 13, row: 11, emoji: '🏰', name: 'Road to the Castle', to: 'castle', toSpawn: { col: 3, row: 9 },
          say: 'To the Champion\'s Castle! 🏰' },
      ],
    },

    meadow: {
      name: 'Multiplication Meadow', emoji: '🌾', tile: 40, spawn: { col: 3, row: 9 },
      legend: { '.': {}, '#': {}, '~': { solid: true }, 'T': { solid: true }, 'H': { solid: true }, '*': {} },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..............T',
        'T..*.......*...T',
        'T.....##.......T',
        'T.....##.......T',
        'T..............T',
        'T....HH.......#T',
        'T....HH.......#T',
        'T..............T',
        'T..*.......*...T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
      objects: [
        { type: 'encounter', col: 8,  row: 5, emoji: '🐰', name: 'Hoppy Bunny', strand: 'Multiplication',
          say: 'Carrots come in bunches — can you count them in groups? 🥕' },
        { type: 'encounter', col: 11, row: 2, emoji: '🐝', name: 'Buzz', strand: 'Numbers & Place Value',
          say: 'So many flowers! Help me put the numbers in order? 🌼' },
        { type: 'boss', col: 8, row: 8, emoji: '🧮', name: 'King Abacus', strand: 'Multiplication',
          id: 'boss-meadow', questions: 3, sticker: { glyph: '🥇', name: 'Abacus Medal' }, reward: { coins: 40, decor: 'decor-telescope' },
          say: 'I am King Abacus! Solve THREE puzzles to pass! 🧮',
          lines: { win: 'Incredible! You are a true mathematician! 🏆', done: 'You already bested me, champion! 👑' } },
        { type: 'warp',      col: 13, row: 6, emoji: '🏙️', name: 'Back to Town', to: 'town', toSpawn: { col: 16, row: 9 },
          say: 'Back to Town Square! 🏙️' },
        { type: 'warp',      col: 2,  row: 2, emoji: '💧', name: 'Trail to the Falls', to: 'falls', toSpawn: { col: 3, row: 9 },
          say: 'To Fraction Falls! 💧' },
      ],
    },

    falls: {
      name: 'Fraction Falls', emoji: '💧', tile: 40, spawn: { col: 3, row: 9 },
      lock: { mastered: 2 }, // a gentle gate: master 2 skills to open the Falls

      legend: { '.': {}, '#': {}, '~': { solid: true }, 'T': { solid: true }, 'H': { solid: true }, '*': {} },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..............T',
        'T...~~~~~~.....T',
        'T...~~~~~~.....T',
        'T..............T',
        'T......##......T',
        'T......##......T',
        'T..............T',
        'T...*......*...T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
      objects: [
        { type: 'encounter', col: 10, row: 8, emoji: '🐸', name: 'Lily the Frog', strand: 'Fractions',
          say: 'The pond is split into parts — can you name the fraction? 🪷' },
        { type: 'boss', col: 7, row: 9, emoji: '🐙', name: 'Professor Octo', strand: 'Fractions',
          id: 'boss-falls', questions: 3, sticker: { glyph: '🐚', name: 'Sea Shell' }, reward: { coins: 45, decor: 'decor-aquarium' },
          say: 'Eight arms, lots of fractions! Solve THREE! 🐙', lines: { win: 'Splendid! Truly fraction-tastic! 🐙🏆', done: 'You already amazed me! 🌊' } },
        { type: 'warp',      col: 13, row: 6, emoji: '🌾', name: 'Trail to the Meadow', to: 'meadow', toSpawn: { col: 2, row: 3 },
          say: 'Back to the Meadow! 🌾' },
      ],
    },

    gardens: {
      name: 'Geometry Gardens', emoji: '🌳', tile: 40, spawn: { col: 3, row: 10 },
      legend: { '.': {}, '#': {}, '~': { solid: true }, 'T': { solid: true }, 'H': { solid: true }, '*': {} },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..............T',
        'T...HH.........T',
        'T...HH.........T',
        'T..............T',
        'T.....*..*.....T',
        'T..............T',
        'T....##........T',
        'T....##........T',
        'T..*........*..T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
      objects: [
        { type: 'encounter', col: 9,  row: 5, emoji: '🐢', name: 'Shelly the Turtle', strand: 'Geometry & Measurement',
          say: 'Let\'s measure and shape things up! 📐' },
        { type: 'boss', col: 7, row: 9, emoji: '🦕', name: 'Geo Rex', strand: 'Geometry & Measurement',
          id: 'boss-gardens', questions: 3, sticker: { glyph: '📐', name: 'Golden Ruler' }, reward: { coins: 45, decor: 'decor-fairy-lights' },
          say: 'RAWR! Measure up to me — solve THREE! 🦕', lines: { win: 'A mighty geometer! 🦕🏆', done: 'You already conquered me! 🌳' } },
        { type: 'warp',      col: 13, row: 9, emoji: '🏙️', name: 'Back to Town', to: 'town', toSpawn: { col: 5, row: 10 },
          say: 'Back to Town Square! 🏙️' },
        { type: 'warp',      col: 2,  row: 2, emoji: '🌊', name: 'Pier to the Docks', to: 'docks', toSpawn: { col: 3, row: 9 },
          say: 'Off to Decimal Docks! 🌊' },
      ],
    },

    docks: {
      name: 'Decimal Docks', emoji: '🌊', tile: 40, spawn: { col: 3, row: 9 },
      lock: { boss: 'boss-gardens' }, // defeat Geo Rex in Geometry Gardens to unlock the Docks (access gate)
      legend: { '.': {}, '#': {}, '~': { solid: true }, 'T': { solid: true }, 'H': { solid: true }, '*': {} },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..............T',
        'T..........~~~~T',
        'T..........~~~~T',
        'T..............T',
        'T....##........T',
        'T....##........T',
        'T..............T',
        'T...*......*...T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
      objects: [
        { type: 'encounter', col: 6,  row: 8, emoji: '🦀', name: 'Sandy the Crab', strand: 'Decimals',
          say: 'Point one, point two… help me line up the dots! 🦀' },
        { type: 'boss', col: 9, row: 9, emoji: '🦈', name: 'Captain Sharky', strand: 'Decimals',
          id: 'boss-docks', questions: 3, sticker: { glyph: '⚓', name: 'Captain\'s Anchor' }, reward: { coins: 50, decor: 'decor-telescope' },
          say: 'Arr! Three decimal puzzles to pass me by! 🦈', lines: { win: 'Ye be a decimal legend! 🦈🏆', done: 'Ye already bested me, matey! ⚓' } },
        { type: 'warp',      col: 13, row: 6, emoji: '🌳', name: 'Pier to the Gardens', to: 'gardens', toSpawn: { col: 3, row: 10 },
          say: 'Back to the Gardens! 🌳' },
      ],
    },

    castle: {
      name: "Champion's Castle", emoji: '🏰', tile: 40, spawn: { col: 3, row: 9 },
      lock: { bosses: 5 }, // open only after beating every zone boss
      legend: { '.': {}, '#': {}, '~': { solid: true }, 'T': { solid: true }, 'H': { solid: true }, '*': {} },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..............T',
        'T...HH....HH...T',
        'T...HH....HH...T',
        'T..............T',
        'T......HH......T',
        'T......HH......T',
        'T..............T',
        'T...*......*...T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
      objects: [
        { type: 'boss', col: 8, row: 9, emoji: '👑', name: 'The Grand Equation', strand: 'Multiplication',
          id: 'boss-castle', questions: 4, sticker: { glyph: '🏆', name: 'Champion Trophy' }, reward: { coins: 100, decor: 'decor-bed' },
          say: 'Only a true champion may pass! Solve FOUR! 👑', lines: { win: 'You have mastered the island! 🏆👑', done: 'All hail the Champion! 👑' } },
        { type: 'warp', col: 13, row: 6, emoji: '🏙️', name: 'Back to Town', to: 'town', toSpawn: { col: 5, row: 10 },
          say: 'Back to Town Square! 🏙️' },
      ],
    },
  },
};
